### ISSUE TITLE
Have characters go back to their idle loop a few frames after displaying a button animation

### ISSUE THREAD

**Issue by xen-osd** [open-manifold/Open-Manifold#13] opened 2023-01-15 19:29 UTC
Currently, the character's animations hang on whatever the last pressed button was and don't go back to idle until the CPU takes over.

**Comment by SuperFromND** [comment] 2023-01-15 20:27
Holding on the button animation frame is intended behavior (I simply thought it looked nicer in motion), but _Rhythm 'n' Face_ does actually change back to idle loop after a period of time (I believe one beat?), so I'll look into it!

**Comment by xen-osd** [comment] 2023-01-15 21:44
If it looks good in some cases, perhaps it could be made a setting?

**Comment by SuperFromND** [comment] 2023-01-15 22:46
I've decided to implement a timer for character states for now; this can always be made into a setting later.

Right now each state is held for a fixed amount of time (400 milliseconds), and I'd like to have it instead be the length of 1 beat relative to the song's BPM in the future, but I'm gonna go ahead and close this for now since it's been implemented. :)

**Closed by SuperFromND** 2023-01-15 22:46 UTC
Labels: enhancement
